# Generated by Django 3.2.7 on 2021-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
